<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (C) 2026 Emvdy; SPDX-License-Identifier: GPL-3.0-or-later -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Psh.CatalogBuilder</AssemblyName>
    <RootNamespace>Psh.CatalogBuilder</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
</Project>
