// Copyright (C) 2026 Emvdy
// SPDX-License-Identifier: GPL-3.0-or-later
// This file is generated by Build-PshSetupExe.ps1. Do not edit by hand.

internal static class EmbeddedResourceHashes
{
    // SHA-256 of Resources\install-offline.ps1 (replaced at build time)
    internal const string OfflineScriptSha256 = "0000000000000000000000000000000000000000000000000000000000000000";

    // SHA-256 of Resources\psh-core.zip (replaced at build time)
    internal const string CoreArchiveSha256 = "0000000000000000000000000000000000000000000000000000000000000000";
}
