# Copyright (C) 2026 Emvdy
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Build-PshSetupExe.ps1 — 一键构建 psh-setup.exe 自包含安装器
#
# 用法:
#   .\scripts\Build-PshSetupExe.ps1 [-CandidateRoot <path>] [-Version <x.y.z>]
#
# 依赖:
#   - dotnet (或 msbuild) 可用
#   - 已生成的 candidate 目录（含 psh-<ver>-core.zip）；
#     如不指定 -CandidateRoot，脚本会先调用 New-Goal6Candidate.ps1 生成。

[CmdletBinding()]
param(
    [string] $CandidateRoot,
    [string] $Version = '0.2.0',
    [string] $RepositoryRoot = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Write-Step {
    param([string] $Message)
    Write-Host "[build-setup-exe] $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string] $Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Compute-Sha256 {
    param([string] $Path)
    $hash = Get-FileHash -Path $Path -Algorithm SHA256
    return $hash.Hash.ToLower()
}

# ── 1. Locate core zip ────────────────────────────────────────────────────────

Write-Step "Locating psh-$Version-core.zip ..."

$coreZipName = "psh-$Version-core.zip"

if ([string]::IsNullOrWhiteSpace($CandidateRoot)) {
    # Try default candidate location next to repo
    $defaultCandidate = Join-Path (Split-Path -Parent $RepositoryRoot) 'candidate'
    if (Test-Path (Join-Path $defaultCandidate $coreZipName)) {
        $CandidateRoot = $defaultCandidate
    } else {
        Write-Host "  No -CandidateRoot supplied and default not found." -ForegroundColor Yellow
        Write-Host "  Please run New-Goal6Candidate.ps1 first, or supply -CandidateRoot." -ForegroundColor Yellow
        throw "Cannot locate $coreZipName. Supply -CandidateRoot."
    }
}

$coreZipPath = Join-Path $CandidateRoot $coreZipName
if (-not (Test-Path $coreZipPath)) {
    throw "Core zip not found: $coreZipPath"
}

Write-Ok "Found: $coreZipPath"

# ── 2. Locate install-offline.ps1 ────────────────────────────────────────────

Write-Step "Locating install-offline.ps1 ..."

$offlineScriptSrc = Join-Path $RepositoryRoot 'src\install\install-offline.ps1'
if (-not (Test-Path $offlineScriptSrc)) {
    throw "install-offline.ps1 not found: $offlineScriptSrc"
}

Write-Ok "Found: $offlineScriptSrc"

# ── 3. Copy resources into src/setup-exe/Resources/ ──────────────────────────

Write-Step "Copying resources ..."

$resourcesDir = Join-Path $RepositoryRoot 'src\setup-exe\Resources'
if (-not (Test-Path $resourcesDir)) {
    New-Item -ItemType Directory -Path $resourcesDir -Force | Out-Null
}

$destZip = Join-Path $resourcesDir 'psh-core.zip'
$destScript = Join-Path $resourcesDir 'install-offline.ps1'

Copy-Item -Path $coreZipPath -Destination $destZip -Force
Copy-Item -Path $offlineScriptSrc -Destination $destScript -Force

Write-Ok "Resources copied."

# ── 4. Compute SHA-256 hashes ─────────────────────────────────────────────────

Write-Step "Computing SHA-256 hashes ..."

$scriptHash = Compute-Sha256 $destScript
$archiveHash = Compute-Sha256 $destZip

Write-Ok "install-offline.ps1 : $scriptHash"
Write-Ok "psh-core.zip        : $archiveHash"

# ── 5. Write EmbeddedResourceHashes.g.cs ─────────────────────────────────────

Write-Step "Writing EmbeddedResourceHashes.g.cs ..."

$hashesFile = Join-Path $RepositoryRoot 'src\setup-exe\EmbeddedResourceHashes.g.cs'
$hashesContent = @"
// Copyright (C) 2026 Emvdy
// SPDX-License-Identifier: GPL-3.0-or-later
// This file is generated by Build-PshSetupExe.ps1. Do not edit by hand.

internal static class EmbeddedResourceHashes
{
    // SHA-256 of Resources\install-offline.ps1 (replaced at build time)
    internal const string OfflineScriptSha256 = "$scriptHash";

    // SHA-256 of Resources\psh-core.zip (replaced at build time)
    internal const string CoreArchiveSha256 = "$archiveHash";
}
"@

[System.IO.File]::WriteAllText($hashesFile, $hashesContent, [System.Text.Encoding]::UTF8)
Write-Ok "Written: $hashesFile"

# ── 6. Build the exe ─────────────────────────────────────────────────────────

Write-Step "Building psh-setup.exe ..."

$csprojPath = Join-Path $RepositoryRoot 'src\setup-exe\Psh.SetupExe.csproj'

# Try dotnet first (SDK-style runner, supports old-style csproj via MSBuild)
$dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
$msbuild = Get-Command msbuild -ErrorAction SilentlyContinue

if ($dotnet) {
    Write-Host "  Using: dotnet build" -ForegroundColor Gray
    $buildOutput = dotnet build $csprojPath -c Release --nologo 2>&1
    $buildExit = $LASTEXITCODE
} elseif ($msbuild) {
    Write-Host "  Using: msbuild" -ForegroundColor Gray
    $buildOutput = msbuild $csprojPath /p:Configuration=Release /nologo 2>&1
    $buildExit = $LASTEXITCODE
} else {
    throw "Neither dotnet nor msbuild was found. Install .NET SDK or Visual Studio Build Tools."
}

if ($buildExit -ne 0) {
    Write-Host ""
    Write-Host "Build output:" -ForegroundColor Yellow
    $buildOutput | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
    throw "Build failed with exit code $buildExit."
}

Write-Ok "Build succeeded."

# ── 7. Locate and report output ───────────────────────────────────────────────

Write-Step "Locating output exe ..."

# 兼容旧 SDK（bin\Release\）和新 SDK（bin\Release\net472\）两种输出路径
$exePath      = Join-Path $RepositoryRoot 'src\setup-exe\bin\Release\psh-setup.exe'
$exePathAlt   = Join-Path $RepositoryRoot 'src\setup-exe\bin\Release\net472\psh-setup.exe'
if (-not (Test-Path $exePath)) {
    if (Test-Path $exePathAlt) {
        $exePath = $exePathAlt
    } else {
        throw "Output exe not found at either expected path:`n  $exePath`n  $exePathAlt"
    }
}

$size = (Get-Item $exePath).Length
Write-Ok "psh-setup.exe : $([math]::Round($size / 1KB, 0)) KB  ($exePath)"

# Optionally copy to candidate root
if (-not [string]::IsNullOrWhiteSpace($CandidateRoot)) {
    $destExe = Join-Path $CandidateRoot 'psh-setup.exe'
    Copy-Item -Path $exePath -Destination $destExe -Force
    Write-Ok "Copied to candidate: $destExe"
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  psh-setup.exe built successfully!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Users can now:" -ForegroundColor Cyan
Write-Host "  1. Download psh-setup.exe (single file, ~$([math]::Round($size / 1MB, 1)) MB)" -ForegroundColor White
Write-Host "  2. Double-click or run: .\psh-setup.exe" -ForegroundColor White
Write-Host "  3. Psh Core installs without admin rights, no extra downloads." -ForegroundColor White
Write-Host ""
