# Copyright (C) 2026 Emvdy
# SPDX-License-Identifier: GPL-3.0-or-later

#Requires -Version 5.1

[CmdletBinding(DefaultParameterSetName = 'Build')]
param(
    [Parameter(Mandatory = $true)]
    [Alias('OnlinePath')]
    [string]$OnlineScriptPath,

    [Parameter(Mandatory = $true)]
    [Alias('OfflinePath')]
    [string]$OfflineScriptPath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Build')]
    [string]$OutputPath,

    [Parameter(ParameterSetName = 'Build')]
    [Parameter(Mandatory = $true, ParameterSetName = 'Generate')]
    [Alias('GeneratedSourcePath')]
    [string]$HashSourcePath,

    [Parameter(Mandatory = $true, ParameterSetName = 'Generate')]
    [Alias('GenerateOnly')]
    [switch]$GenerateHashSourceOnly,

    [Parameter(ParameterSetName = 'Build')]
    [string]$MSBuildPath
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

function Throw-PshBootstrapperBuildError {
    param([Parameter(Mandatory = $true)][string]$Message)
    throw ('Psh bootstrapper build failed: {0}' -f $Message)
}

function Resolve-PshFilePath {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Description
    )

    try {
        $resolved = Resolve-Path -LiteralPath $Path -ErrorAction Stop
    }
    catch {
        Throw-PshBootstrapperBuildError ('{0} was not found: {1}' -f $Description, $Path)
    }

    if ($resolved.Provider.Name -ne 'FileSystem') {
        Throw-PshBootstrapperBuildError ('{0} is not a file-system path: {1}' -f $Description, $Path)
    }

    $fullPath = [IO.Path]::GetFullPath($resolved.ProviderPath)
    if (-not [IO.File]::Exists($fullPath)) {
        Throw-PshBootstrapperBuildError ('{0} is not a regular file: {1}' -f $Description, $fullPath)
    }

    return $fullPath
}

function Get-PshSha256File {
    param([Parameter(Mandatory = $true)][string]$Path)

    $sha256 = [Security.Cryptography.SHA256]::Create()
    $stream = [IO.File]::OpenRead($Path)
    try {
        return ([BitConverter]::ToString($sha256.ComputeHash($stream))).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $stream.Dispose()
        $sha256.Dispose()
    }
}

function Write-PshHashSource {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$OnlineHash,
        [Parameter(Mandatory = $true)][string]$OfflineHash
    )

    if ($Path -notmatch '\.cs\z') {
        Throw-PshBootstrapperBuildError ('Hash source path must end in .cs: {0}' -f $Path)
    }

    $parent = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        [void][IO.Directory]::CreateDirectory($parent)
    }

    $source = @"
// Copyright (C) 2026 Emvdy
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/Build-PshBootstrapper.ps1; do not edit by hand.

namespace Psh.Bootstrapper
{
    internal static class EmbeddedScriptHashes
    {
        internal const string OnlineScriptSha256 = "$OnlineHash";
        internal const string OfflineScriptSha256 = "$OfflineHash";
    }
}
"@

    $utf8 = New-Object System.Text.UTF8Encoding -ArgumentList @($false, $true)
    [IO.File]::WriteAllText($Path, $source.Replace("`r`n", "`n").Replace("`r", "`n"), $utf8)
}

function Resolve-PshMSBuild {
    param([string]$RequestedPath)

    if (-not [string]::IsNullOrWhiteSpace($RequestedPath)) {
        $explicit = Resolve-PshFilePath -Path $RequestedPath -Description 'MSBuild executable'
        if ([IO.Path]::GetFileName($explicit) -ine 'MSBuild.exe') {
            Throw-PshBootstrapperBuildError ('MSBuild path must name MSBuild.exe: {0}' -f $explicit)
        }

        return $explicit
    }

    $candidates = New-Object System.Collections.Generic.List[string]
    $command = Get-Command -Name 'MSBuild.exe' -CommandType Application -ErrorAction SilentlyContinue
    if ($null -ne $command -and $command.Source) {
        [void]$candidates.Add([string]$command.Source)
    }

    $programFilesX86 = [Environment]::GetFolderPath([Environment+SpecialFolder]::ProgramFilesX86)
    $programFiles = [Environment]::GetFolderPath([Environment+SpecialFolder]::ProgramFiles)
    foreach ($programRoot in @($programFilesX86, $programFiles)) {
        if ([string]::IsNullOrWhiteSpace($programRoot)) { continue }
        foreach ($year in @('2022', '2019')) {
            foreach ($edition in @('Enterprise', 'Professional', 'Community', 'BuildTools')) {
                [void]$candidates.Add((Join-Path $programRoot (Join-Path 'Microsoft Visual Studio' (Join-Path $year (Join-Path $edition 'MSBuild\Current\Bin\MSBuild.exe')))))
            }
        }
    }

    foreach ($candidate in $candidates) {
        if ([IO.File]::Exists($candidate)) {
            return [IO.Path]::GetFullPath($candidate)
        }
    }

    Throw-PshBootstrapperBuildError 'A Visual Studio MSBuild.exe (with the classic .NET Framework targets) was not found.'
}

$onlinePath = Resolve-PshFilePath -Path $OnlineScriptPath -Description 'online installer script'
$offlinePath = Resolve-PshFilePath -Path $OfflineScriptPath -Description 'offline installer script'
if ([IO.Path]::GetFileName($onlinePath) -ine 'install.ps1') {
    Throw-PshBootstrapperBuildError ('Online script must be named install.ps1: {0}' -f $onlinePath)
}
if ([IO.Path]::GetFileName($offlinePath) -ine 'install-offline.ps1') {
    Throw-PshBootstrapperBuildError ('Offline script must be named install-offline.ps1: {0}' -f $offlinePath)
}
if ([string]::Equals($onlinePath, $offlinePath, [StringComparison]::OrdinalIgnoreCase)) {
    Throw-PshBootstrapperBuildError 'Online and offline script paths must be different files.'
}

$onlineHash = Get-PshSha256File -Path $onlinePath
$offlineHash = Get-PshSha256File -Path $offlinePath
$placeholderHash = '0' * 64
if ($onlineHash -notmatch '\A[0-9a-f]{64}\z' -or $offlineHash -notmatch '\A[0-9a-f]{64}\z' -or
    $onlineHash -ceq $placeholderHash -or $offlineHash -ceq $placeholderHash) {
    Throw-PshBootstrapperBuildError 'A script SHA256 value was invalid or equal to the fail-closed placeholder.'
}

$hashSource = if ([string]::IsNullOrWhiteSpace($HashSourcePath)) {
    $null
}
else {
    [IO.Path]::GetFullPath($HashSourcePath)
}

$temporaryRoot = $null
$temporaryHashSource = $false
try {
    if ($null -eq $hashSource) {
        $temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ('psh-bootstrapper-build-' + [Guid]::NewGuid().ToString('N'))
        [void][IO.Directory]::CreateDirectory($temporaryRoot)
        $hashSource = Join-Path $temporaryRoot 'EmbeddedScriptHashes.g.cs'
        $temporaryHashSource = $true
    }

    Write-PshHashSource -Path $hashSource -OnlineHash $onlineHash -OfflineHash $offlineHash

    if ($GenerateHashSourceOnly) {
        Write-Output ('Generated embedded hash source: {0}' -f $hashSource)
        return
    }

    if ([Environment]::OSVersion.Platform -ne [PlatformID]::Win32NT) {
        Throw-PshBootstrapperBuildError 'The classic .NET Framework bootstrapper can only be compiled on Windows.'
    }

    if ([string]::IsNullOrWhiteSpace($OutputPath)) {
        Throw-PshBootstrapperBuildError 'OutputPath is required when compiling the bootstrapper.'
    }

    $outputFullPath = [IO.Path]::GetFullPath($OutputPath)
    if ([IO.Path]::GetExtension($outputFullPath) -ine '.exe') {
        Throw-PshBootstrapperBuildError ('Output path must end in .exe: {0}' -f $outputFullPath)
    }

    $temporaryRootForBuild = Join-Path ([IO.Path]::GetTempPath()) ('psh-bootstrapper-msbuild-' + [Guid]::NewGuid().ToString('N'))
    [void][IO.Directory]::CreateDirectory($temporaryRootForBuild)
    $buildOutput = Join-Path $temporaryRootForBuild 'bin\'
    $buildIntermediate = Join-Path $temporaryRootForBuild 'obj\'
    [void][IO.Directory]::CreateDirectory($buildOutput)
    [void][IO.Directory]::CreateDirectory($buildIntermediate)

    try {
        $projectPath = Join-Path $PSScriptRoot '..\src\bootstrapper\Psh.Bootstrapper.csproj'
        $projectPath = Resolve-PshFilePath -Path $projectPath -Description 'bootstrapper project'
        $msbuild = Resolve-PshMSBuild -RequestedPath $MSBuildPath
        $msbuildArguments = @(
            $projectPath,
            '/nologo',
            '/verbosity:minimal',
            '/t:Build',
            '/p:Configuration=Release',
            '/p:Platform=AnyCPU',
            ('/p:PshEmbeddedHashesSource={0}' -f $hashSource),
            ('/p:OutputPath={0}' -f $buildOutput),
            ('/p:BaseIntermediateOutputPath={0}' -f $buildIntermediate),
            ('/p:IntermediateOutputPath={0}' -f $buildIntermediate)
        )

        # There is deliberately one compiler-driver invocation per build. The
        # generated hash source is passed as a project property in that build.
        $buildOutputText = @(& $msbuild @msbuildArguments 2>&1)
        $buildExitCode = if ($null -eq $LASTEXITCODE) { 0 } else { [int]$LASTEXITCODE }
        if ($buildExitCode -ne 0) {
            $diagnostic = (($buildOutputText | ForEach-Object { [string]$_ }) -join "`n").Trim()
            if ($diagnostic.Length -gt 4000) { $diagnostic = $diagnostic.Substring($diagnostic.Length - 4000) }
            Throw-PshBootstrapperBuildError ('MSBuild exited {0}: {1}' -f $buildExitCode, $diagnostic)
        }

        $builtExe = Join-Path $buildOutput 'psh-installer.exe'
        if (-not [IO.File]::Exists($builtExe)) {
            Throw-PshBootstrapperBuildError ('MSBuild completed without producing {0}.' -f $builtExe)
        }

        $outputParent = Split-Path -Parent $outputFullPath
        if (-not [string]::IsNullOrWhiteSpace($outputParent)) {
            [void][IO.Directory]::CreateDirectory($outputParent)
        }
        Copy-Item -LiteralPath $builtExe -Destination $outputFullPath -Force
        Write-Output ('Built deterministic AnyCPU bootstrapper: {0}' -f $outputFullPath)
    }
    finally {
        if (Test-Path -LiteralPath $temporaryRootForBuild -PathType Container) {
            Remove-Item -LiteralPath $temporaryRootForBuild -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}
finally {
    if ($temporaryHashSource -and $null -ne $temporaryRoot -and (Test-Path -LiteralPath $temporaryRoot -PathType Container)) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}
